INSERT INTO kra_definitions (discipline, kra_name, kra_number, sub_kra_name, level, description) VALUES
('creative-copy-art', 'Ideation', 1, 'Big Idea', 'L1', 'NIL'),
('creative-copy-art', 'Ideation', 1, 'Big Idea', 'L2', 'Display shades of big idea'),
('creative-copy-art', 'Ideation', 1, 'Big Idea', 'L3', 'Demostrate Big idea thinking'),
('creative-copy-art', 'Ideation', 1, 'Big Idea', 'L4', 'Demostrate Big idea thinking often'),
('creative-copy-art', 'Ideation', 1, 'Big Idea', 'L5', 'Demostrate Big idea thinking more often'),
('creative-copy-art', 'Ideation', 1, 'Big Idea', 'L6', 'Demostrate Big idea thinking more often'),
('creative-copy-art', 'Ideation', 1, 'Sideways Thinking - Originality and Freshness', 'L1', 'Sideways Thinking - Originality and Freshness'),
('creative-copy-art', 'Ideation', 1, 'Sideways Thinking - Originality and Freshness', 'L2', 'Sideways Thinking - Originality and Freshness'),
('creative-copy-art', 'Ideation', 1, 'Sideways Thinking - Originality and Freshness', 'L3', 'Sideways Thinking - Originality and Freshness'),
('creative-copy-art', 'Ideation', 1, 'Sideways Thinking - Originality and Freshness', 'L4', 'Sideways Thinking - Originality and Freshness - a must'),
('creative-copy-art', 'Ideation', 1, 'Sideways Thinking - Originality and Freshness', 'L5', 'Sideways Thinking - Originality and Freshness - a must'),
('creative-copy-art', 'Ideation', 1, 'Sideways Thinking - Originality and Freshness', 'L6', 'Sideways Thinking - Originality and Freshness - a must'),
('creative-copy-art', 'Ideation', 1, 'Width of exploration - tone, audience, approaches', 'L1', 'Understanding of range of ideation'),
('creative-copy-art', 'Ideation', 1, 'Width of exploration - tone, audience, approaches', 'L2', 'Demostrate width of exploration'),
('creative-copy-art', 'Ideation', 1, 'Width of exploration - tone, audience, approaches', 'L3', 'Width of exploration - tone, audience, approaches'),
('creative-copy-art', 'Ideation', 1, 'Width of exploration - tone, audience, approaches', 'L4', 'Width of exploration - tone, audience, approaches - more often'),
('creative-copy-art', 'Ideation', 1, 'Width of exploration - tone, audience, approaches', 'L5', 'Width of exploration - tone, audience, approaches - more often'),
('creative-copy-art', 'Ideation', 1, 'Width of exploration - tone, audience, approaches', 'L6', 'Width of exploration - tone, audience, approaches - more often'),
('creative-copy-art', 'Ideation', 1, 'Maturity of Ideas', 'L1', 'NIL'),
('creative-copy-art', 'Ideation', 1, 'Maturity of Ideas', 'L2', 'Basic level of maturity of ideas'),
('creative-copy-art', 'Ideation', 1, 'Maturity of Ideas', 'L3', 'NIL'),
('creative-copy-art', 'Ideation', 1, 'Maturity of Ideas', 'L4', 'Maturity of ideas - advanced level'),
('creative-copy-art', 'Ideation', 1, 'Maturity of Ideas', 'L5', 'Maturity of ideas - spot on.'),
('creative-copy-art', 'Ideation', 1, 'Maturity of Ideas', 'L6', 'Maturity of ideas - spot on.'),
('creative-copy-art', 'Ideation', 1, 'Judgement', 'L1', 'NIL'),
('creative-copy-art', 'Ideation', 1, 'Judgement', 'L2', 'Somewhat have judgement'),
('creative-copy-art', 'Ideation', 1, 'Judgement', 'L3', 'Judgment of work on Brand, on brief, and whether it makes the cut'),
('creative-copy-art', 'Ideation', 1, 'Judgement', 'L4', 'Judgement of whether the work will land impact, bring fame, last for years.'),
('creative-copy-art', 'Ideation', 1, 'Judgement', 'L5', 'Judgement of whether the work will land impact, scale, fame, last for years.'),
('creative-copy-art', 'Ideation', 1, 'Judgement', 'L6', 'Judgement of whether the work will land impact, scale, fame, last for years.'),
('creative-copy-art', 'Ideation', 1, 'Understanding of the strategy - On brief ideas', 'L1', 'Understanding of brief, seek clarification'),
('creative-copy-art', 'Ideation', 1, 'Understanding of the strategy - On brief ideas', 'L2', 'Understanding of brief'),
('creative-copy-art', 'Ideation', 1, 'Understanding of the strategy - On brief ideas', 'L3', 'Understanding of the strategy - On brief ideas'),
('creative-copy-art', 'Ideation', 1, 'Understanding of the strategy - On brief ideas', 'L4', 'Understand the nuances of the strategy and be able to spring board from the brief'),
('creative-copy-art', 'Ideation', 1, 'Understanding of the strategy - On brief ideas', 'L5', 'Understand the nuances of the strategy, be able to further input and fine tune, and find the right expression of all aspects of the brand world. Be able to hold strategic conversations with the senior Clients'),
('creative-copy-art', 'Ideation', 1, 'Understanding of the strategy - On brief ideas', 'L6', 'Understand the nuances of the strategy, be able to further input and fine tune, and find the right expression of all aspects of the brand world. Be able to hold strategic conversations with the senior Clients'),
('creative-copy-art', 'Ideation', 1, 'Cross media ideas', 'L1', 'Understanding of cross media'),
('creative-copy-art', 'Ideation', 1, 'Cross media ideas', 'L2', 'Understanding of cross media and some attempts'),
('creative-copy-art', 'Ideation', 1, 'Cross media ideas', 'L3', 'Explore cross media ideas often'),
('creative-copy-art', 'Ideation', 1, 'Cross media ideas', 'L4', 'Wide exploration of cross media ideas'),
('creative-copy-art', 'Ideation', 1, 'Cross media ideas', 'L5', 'Do and inspire cross media ideas'),
('creative-copy-art', 'Ideation', 1, 'Cross media ideas', 'L6', 'Do and inspire cross media ideas'),
('creative-copy-art', 'Ideation', 1, 'Speed of ideation', 'L1', 'Come to meetings with ideas'),
('creative-copy-art', 'Ideation', 1, 'Speed of ideation', 'L2', 'Speed of ideation'),
('creative-copy-art', 'Ideation', 1, 'Speed of ideation', 'L3', 'Speed of ideation'),
('creative-copy-art', 'Ideation', 1, 'Speed of ideation', 'L4', 'Speed of ideation across projects'),
('creative-copy-art', 'Ideation', 1, 'Speed of ideation', 'L5', 'Speed of ideation'),
('creative-copy-art', 'Ideation', 1, 'Speed of ideation', 'L6', 'Speed of ideation'),
('creative-copy-art', 'Craft', 2, 'Freshness and originality', 'L1', 'Freshness and Originality'),
('creative-copy-art', 'Craft', 2, 'Freshness and originality', 'L2', 'Freshness and Originality'),
('creative-copy-art', 'Craft', 2, 'Freshness and originality', 'L3', 'Freshness and originality'),
('creative-copy-art', 'Craft', 2, 'Freshness and originality', 'L4', 'Freshness and originality'),
('creative-copy-art', 'Craft', 2, 'Freshness and originality', 'L5', 'Freshness and originality that the world recognises. Setting benchmarks for team.'),
('creative-copy-art', 'Craft', 2, 'Freshness and originality', 'L6', 'Freshness and originality that the world recognises. Setting benchmarks for team.'),
('creative-copy-art', 'Craft', 2, 'Variety of styles', 'L1', 'Variety of styles'),
('creative-copy-art', 'Craft', 2, 'Variety of styles', 'L2', 'Variety of styles'),
('creative-copy-art', 'Craft', 2, 'Variety of styles', 'L3', 'Variety of styles often'),
('creative-copy-art', 'Craft', 2, 'Variety of styles', 'L4', 'Variety of styles constistently'),
('creative-copy-art', 'Craft', 2, 'Variety of styles', 'L5', 'Variety of styles constistently'),
('creative-copy-art', 'Craft', 2, 'Variety of styles', 'L6', 'Variety of styles constistently'),
('creative-copy-art', 'Craft', 2, 'Speed of execution', 'L1', 'Awareness of deadline'),
('creative-copy-art', 'Craft', 2, 'Speed of execution', 'L2', 'Timely delivery and management'),
('creative-copy-art', 'Craft', 2, 'Speed of execution', 'L3', 'Speed of execution a must'),
('creative-copy-art', 'Craft', 2, 'Speed of execution', 'L4', 'Speed of execution'),
('creative-copy-art', 'Craft', 2, 'Speed of execution', 'L5', 'Speed of execution'),
('creative-copy-art', 'Craft', 2, 'Speed of execution', 'L6', 'Speed of execution'),
('creative-copy-art', 'Execution', 3, 'External partner choices', 'L1', 'Study of external partners and their work'),
('creative-copy-art', 'Execution', 3, 'External partner choices', 'L2', 'Study of external partners and their work'),
('creative-copy-art', 'Execution', 3, 'External partner choices', 'L3', 'Knowledge of external partner choices and their genres - PH for films, Digital content, Photographers, system correctors'),
('creative-copy-art', 'Execution', 3, 'External partner choices', 'L4', 'Be on the lookout and cultivate new partners. Get the choice of partners right to order for exemplary execution'),
('creative-copy-art', 'Execution', 3, 'External partner choices', 'L5', 'Buiding a bank of fresh talent across. Being able to impact costs and timeliens with partners.'),
('creative-copy-art', 'Execution', 3, 'External partner choices', 'L6', 'Buiding a bank of fresh talent across. Being able to impact costs and timeliens with partners.'),
('creative-copy-art', 'Execution', 3, 'Deliver Solo', 'L1', 'Demonstating proficiency with softwares'),
('creative-copy-art', 'Execution', 3, 'Deliver Solo', 'L2', 'Demonstating proficiency with softwares'),
('creative-copy-art', 'Execution', 3, 'Deliver Solo', 'L3', 'Independant handling of day to day basic Brand briefs'),
('creative-copy-art', 'Execution', 3, 'Deliver Solo', 'L4', 'Deliver solo and know when to upward delegate'),
('creative-copy-art', 'Execution', 3, 'Deliver Solo', 'L5', 'Carry team and deliver independantly'),
('creative-copy-art', 'Execution', 3, 'Deliver Solo', 'L6', 'Carry team and deliver independantly'),
('creative-copy-art', 'Execution', 3, 'Make it happen', 'L1', 'Timely delivery'),
('creative-copy-art', 'Execution', 3, 'Make it happen', 'L2', 'Timely delivery'),
('creative-copy-art', 'Execution', 3, 'Make it happen', 'L3', 'Make it happen and drive closure'),
('creative-copy-art', 'Execution', 3, 'Make it happen', 'L4', 'Make it happen as desired and smoothly'),
('creative-copy-art', 'Execution', 3, 'Make it happen', 'L5', 'Make it happen'),
('creative-copy-art', 'Execution', 3, 'Make it happen', 'L6', 'Make it happen'),
('creative-copy-art', 'Execution', 3, 'Collaboration', 'L1', 'Building awareness of different disciplines'),
('creative-copy-art', 'Execution', 3, 'Collaboration', 'L2', 'Actively collaborate to drive output'),
('creative-copy-art', 'Execution', 3, 'Collaboration', 'L3', 'Actively collaborate to drive output'),
('creative-copy-art', 'Execution', 3, 'Collaboration', 'L4', 'Actively collaborate to drive output'),
('creative-copy-art', 'Execution', 3, 'Collaboration', 'L5', 'Create opportunities for internal collabs through cross functional ideation'),
('creative-copy-art', 'Execution', 3, 'Collaboration', 'L6', 'Create opportunities for internal collabs through cross functional ideation'),
('creative-copy-art', 'Presentation Skills', 4, 'On time readiness', 'L1', 'Writing out the concept/idea/script'),
('creative-copy-art', 'Presentation Skills', 4, 'On time readiness', 'L2', 'On time readiness'),
('creative-copy-art', 'Presentation Skills', 4, 'On time readiness', 'L3', 'On time readiness - rehearsed and ready'),
('creative-copy-art', 'Presentation Skills', 4, 'On time readiness', 'L4', 'Proficient at both verbal and written presentations with minimal inputs'),
('creative-copy-art', 'Presentation Skills', 4, 'On time readiness', 'L5', 'Present to sell.'),
('creative-copy-art', 'Presentation Skills', 4, 'On time readiness', 'L6', 'Present to sell.'),
('creative-copy-art', 'Presentation Skills', 4, 'Verbal', 'L1', 'Understanding what it takes to make a good presentation'),
('creative-copy-art', 'Presentation Skills', 4, 'Verbal', 'L2', 'Make presentations off and on - internal and external'),
('creative-copy-art', 'Presentation Skills', 4, 'Verbal', 'L3', 'Good presentation skills'),
('creative-copy-art', 'Presentation Skills', 4, 'Verbal', 'L4', 'NIL'),
('creative-copy-art', 'Presentation Skills', 4, 'Verbal', 'L5', 'Package strategically.'),
('creative-copy-art', 'Presentation Skills', 4, 'Verbal', 'L6', 'Package strategically.'),
('creative-copy-art', 'Presentation Skills', 4, 'Creating the presentation', 'L1', 'NIL'),
('creative-copy-art', 'Presentation Skills', 4, 'Creating the presentation', 'L2', 'Helping create the presentation for seniors'),
('creative-copy-art', 'Presentation Skills', 4, 'Creating the presentation', 'L3', 'Independantly building the deck'),
('creative-copy-art', 'Presentation Skills', 4, 'Creating the presentation', 'L4', 'NIL'),
('creative-copy-art', 'Presentation Skills', 4, 'Creating the presentation', 'L5', 'NIL'),
('creative-copy-art', 'Presentation Skills', 4, 'Creating the presentation', 'L6', 'NIL'),
('creative-copy-art', 'Bandwidth', 5, 'Number of projects', 'L1', '2 projects'),
('creative-copy-art', 'Bandwidth', 5, 'Number of projects', 'L2', '2-3 projects'),
('creative-copy-art', 'Bandwidth', 5, 'Number of projects', 'L3', '3 to 4 projects'),
('creative-copy-art', 'Bandwidth', 5, 'Number of projects', 'L4', '4-5 projects'),
('creative-copy-art', 'Bandwidth', 5, 'Number of projects', 'L5', '5-6 projects'),
('creative-copy-art', 'Bandwidth', 5, 'Number of projects', 'L6', '5-6 projects'),
('creative-copy-art', 'Leadership', 6, 'Finding the right talent', 'L1', 'NIL'),
('creative-copy-art', 'Leadership', 6, 'Finding the right talent', 'L2', 'NIL'),
('creative-copy-art', 'Leadership', 6, 'Finding the right talent', 'L3', 'NIL'),
('creative-copy-art', 'Leadership', 6, 'Finding the right talent', 'L4', 'Keep a look out for interesting talent'),
('creative-copy-art', 'Leadership', 6, 'Finding the right talent', 'L5', 'Build a team keeping in mind the right structire and right composition of talent'),
('creative-copy-art', 'Leadership', 6, 'Finding the right talent', 'L6', 'Build a team keeping in mind the right structire and right composition of talent'),
('creative-copy-art', 'Leadership', 6, 'Coaching and mentoring the talent', 'L1', 'NIL'),
('creative-copy-art', 'Leadership', 6, 'Coaching and mentoring the talent', 'L2', 'NIL'),
('creative-copy-art', 'Leadership', 6, 'Coaching and mentoring the talent', 'L3', 'Coaching and mentoring the talent'),
('creative-copy-art', 'Leadership', 6, 'Coaching and mentoring the talent', 'L4', 'Coaching and mentoring the talent'),
('creative-copy-art', 'Leadership', 6, 'Coaching and mentoring the talent', 'L5', 'Spending ample time coaching and mentoring the talent'),
('creative-copy-art', 'Leadership', 6, 'Coaching and mentoring the talent', 'L6', 'Spending ample time coaching and mentoring the talent'),
('creative-copy-art', 'Leadership', 6, 'Collaboration', 'L1', 'Demonstrate collaboration spirit'),
('creative-copy-art', 'Leadership', 6, 'Collaboration', 'L2', 'Demonstrate collaboration spirit'),
('creative-copy-art', 'Leadership', 6, 'Collaboration', 'L3', 'NIL'),
('creative-copy-art', 'Leadership', 6, 'Collaboration', 'L4', 'NIL'),
('creative-copy-art', 'Leadership', 6, 'Collaboration', 'L5', 'NIL'),
('creative-copy-art', 'Leadership', 6, 'Collaboration', 'L6', 'NIL'),
('creative-copy-art', 'Leadership', 6, 'Sideways ambassador - Sharing the agency work.', 'L1', 'Sideways ambassador'),
('creative-copy-art', 'Leadership', 6, 'Sideways ambassador - Sharing the agency work.', 'L2', 'Sideways ambassador'),
('creative-copy-art', 'Leadership', 6, 'Sideways ambassador - Sharing the agency work.', 'L3', 'Sideways ambassador'),
('creative-copy-art', 'Leadership', 6, 'Sideways ambassador - Sharing the agency work.', 'L4', 'Sideways ambassador'),
('creative-copy-art', 'Leadership', 6, 'Sideways ambassador - Sharing the agency work.', 'L5', 'Sideways ambassador - Sharing the agency work.'),
('creative-copy-art', 'Leadership', 6, 'Sideways ambassador - Sharing the agency work.', 'L6', 'Sideways ambassador - Sharing the agency work.'),
('creative-copy-art', 'Leadership', 6, 'Champion of ideas', 'L1', 'NIL'),
('creative-copy-art', 'Leadership', 6, 'Champion of ideas', 'L2', 'NIL'),
('creative-copy-art', 'Leadership', 6, 'Champion of ideas', 'L3', 'Being passionate about executing ideas of juniors/crosss functional ideas'),
('creative-copy-art', 'Leadership', 6, 'Champion of ideas', 'L4', 'Spot and Champion ideas'),
('creative-copy-art', 'Leadership', 6, 'Champion of ideas', 'L5', 'Champoin of ideas'),
('creative-copy-art', 'Leadership', 6, 'Champion of ideas', 'L6', 'Champoin of ideas'),
('creative-copy-art', 'Leadership', 6, 'Building stars', 'L1', 'NIL'),
('creative-copy-art', 'Leadership', 6, 'Building stars', 'L2', 'NIL'),
('creative-copy-art', 'Leadership', 6, 'Building stars', 'L3', 'NIL'),
('creative-copy-art', 'Leadership', 6, 'Building stars', 'L4', 'Building stars'),
('creative-copy-art', 'Leadership', 6, 'Building stars', 'L5', 'Building stars'),
('creative-copy-art', 'Leadership', 6, 'Building stars', 'L6', 'Building stars'),
('creative-copy-art', 'Leadership', 6, 'Pressure handling', 'L1', 'NIL'),
('creative-copy-art', 'Leadership', 6, 'Pressure handling', 'L2', 'Pressure handling'),
('creative-copy-art', 'Leadership', 6, 'Pressure handling', 'L3', 'Pressure handling'),
('creative-copy-art', 'Leadership', 6, 'Pressure handling', 'L4', 'Pressure handling'),
('creative-copy-art', 'Leadership', 6, 'Pressure handling', 'L5', 'Pressure handling'),
('creative-copy-art', 'Leadership', 6, 'Pressure handling', 'L6', 'Pressure handling'),
('creative-copy-art', 'Relationships', 7, 'Internal and external', 'L1', 'Building internal relationships across disciplines'),
('creative-copy-art', 'Relationships', 7, 'Internal and external', 'L2', 'Smooth and fruitful internal interactions across disciplines'),
('creative-copy-art', 'Relationships', 7, 'Internal and external', 'L3', 'Solid at managing internal relationships'),
('creative-copy-art', 'Relationships', 7, 'Internal and external', 'L4', 'Solid at managing internal relationships'),
('creative-copy-art', 'Relationships', 7, 'Internal and external', 'L5', 'Solid at managing internal relationships'),
('creative-copy-art', 'Relationships', 7, 'Internal and external', 'L6', 'Solid at managing internal relationships'),
('creative-copy-art', 'Relationships', 7, 'Learning syllabus', 'L1', 'Learning syllabus'),
('creative-copy-art', 'Relationships', 7, 'Learning syllabus', 'L2', 'Learning syllabus'),
('creative-copy-art', 'Relationships', 7, 'Learning syllabus', 'L3', 'Learning syllabus'),
('creative-copy-art', 'Relationships', 7, 'Learning syllabus', 'L4', 'Learning syllabus'),
('creative-copy-art', 'Relationships', 7, 'Learning syllabus', 'L5', 'Should engage with the Client off briefs as well - find their way of building a personal relationship with the mid to senior level Clients'),
('creative-copy-art', 'Relationships', 7, 'Learning syllabus', 'L6', 'Should engage with the Client off briefs as well - find their way of building a personal relationship with the mid to senior level Clients'),
('creative-copy-art', 'Softer Skills', 8, 'Sideways person', 'L1', 'NIL'),
('creative-copy-art', 'Softer Skills', 8, 'Sideways person', 'L2', 'NIL'),
('creative-copy-art', 'Softer Skills', 8, 'Sideways person', 'L3', 'NIL'),
('creative-copy-art', 'Softer Skills', 8, 'Sideways person', 'L4', 'NIL'),
('creative-copy-art', 'Softer Skills', 8, 'Sideways person', 'L5', 'Build a positive environment.'),
('creative-copy-art', 'Softer Skills', 8, 'Sideways person', 'L6', 'Build a positive environment.'),
('creative-copy-art', 'Softer Skills', 8, 'Attitude to excellence', 'L1', 'NIL'),
('creative-copy-art', 'Softer Skills', 8, 'Attitude to excellence', 'L2', 'NIL'),
('creative-copy-art', 'Softer Skills', 8, 'Attitude to excellence', 'L3', 'NIL'),
('creative-copy-art', 'Softer Skills', 8, 'Attitude to excellence', 'L4', 'NIL'),
('creative-copy-art', 'Softer Skills', 8, 'Attitude to excellence', 'L5', 'NIL'),
('creative-copy-art', 'Softer Skills', 8, 'Attitude to excellence', 'L6', 'NIL'),
('creative-copy-art', 'Softer Skills', 8, 'Hunger/Drive', 'L1', 'NIL'),
('creative-copy-art', 'Softer Skills', 8, 'Hunger/Drive', 'L2', 'NIL'),
('creative-copy-art', 'Softer Skills', 8, 'Hunger/Drive', 'L3', 'NIL'),
('creative-copy-art', 'Softer Skills', 8, 'Hunger/Drive', 'L4', 'NIL'),
('creative-copy-art', 'Softer Skills', 8, 'Hunger/Drive', 'L5', 'NIL'),
('creative-copy-art', 'Softer Skills', 8, 'Hunger/Drive', 'L6', 'NIL'),
('creative-copy-art', 'Softer Skills', 8, 'Temperament', 'L1', 'NIL'),
('creative-copy-art', 'Softer Skills', 8, 'Temperament', 'L2', 'NIL'),
('creative-copy-art', 'Softer Skills', 8, 'Temperament', 'L3', 'NIL'),
('creative-copy-art', 'Softer Skills', 8, 'Temperament', 'L4', 'NIL'),
('creative-copy-art', 'Softer Skills', 8, 'Temperament', 'L5', 'NIL'),
('creative-copy-art', 'Softer Skills', 8, 'Temperament', 'L6', 'NIL'),
('creative-copy-art', 'Softer Skills', 8, 'Work ethic', 'L1', 'NIL'),
('creative-copy-art', 'Softer Skills', 8, 'Work ethic', 'L2', 'NIL'),
('creative-copy-art', 'Softer Skills', 8, 'Work ethic', 'L3', 'NIL'),
('creative-copy-art', 'Softer Skills', 8, 'Work ethic', 'L4', 'NIL'),
('creative-copy-art', 'Softer Skills', 8, 'Work ethic', 'L5', 'NIL'),
('creative-copy-art', 'Softer Skills', 8, 'Work ethic', 'L6', 'NIL'),
('creative-copy-art', 'Softer Skills', 8, 'Mutual respect', 'L1', 'NIL'),
('creative-copy-art', 'Softer Skills', 8, 'Mutual respect', 'L2', 'NIL'),
('creative-copy-art', 'Softer Skills', 8, 'Mutual respect', 'L3', 'NIL'),
('creative-copy-art', 'Softer Skills', 8, 'Mutual respect', 'L4', 'NIL'),
('creative-copy-art', 'Softer Skills', 8, 'Mutual respect', 'L5', 'NIL'),
('creative-copy-art', 'Softer Skills', 8, 'Mutual respect', 'L6', 'NIL'),
('creative-copy-art', 'Softer Skills', 8, 'Learning', 'L1', 'NIL'),
('creative-copy-art', 'Softer Skills', 8, 'Learning', 'L2', 'NIL'),
('creative-copy-art', 'Softer Skills', 8, 'Learning', 'L3', 'NIL'),
('creative-copy-art', 'Softer Skills', 8, 'Learning', 'L4', 'NIL'),
('creative-copy-art', 'Softer Skills', 8, 'Learning', 'L5', 'NIL'),
('creative-copy-art', 'Softer Skills', 8, 'Learning', 'L6', 'NIL');